services:
  server:
    build: .
    ports: 
      - 7788:${ACC_APP_PORT}
      - 7789:${MM_APP_PORT}
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      ACC_APP_ENV: ${ACC_APP_ENV:-DEVEL}
      ACC_APP_PORT: ${ACC_APP_PORT:-8000}
      ACC_ACCESS_TOKEN_SECRET: ${ACC_ACCESS_TOKEN_SECRET:-you_wouldnt_guess_it}
      ACC_ACCESS_TOKEN_LIFETIME: ${ACC_ACCESS_TOKEN_LIFETIME:-10}
      ACC_REFRESH_TOKEN_SECRET: ${ACC_REFRESH_TOKEN_SECRET:-quit_it_its_no_use}
      ACC_REFRESH_TOKEN_LIFETIME: ${ACC_REFRESH_TOKEN_LIFETIME:-10}
      ACC_AUTH_MAX_FAIL: ${ACC_AUTH_MAX_FAIL:-3}
      ACC_AUTH_FAIL_COOLDOWN: ${ACC_AUTH_FAIL_COOLDOWN:-10}
      ACC_DB_URL: ${ACC_DB_URL:-postgresql://postgres:dont_you_have_something_better_to_do@account-db:5432/mydb?schema=public}
      ACC_CACHE_URL: ${ACC_CACHE_URL:-redis://:dont_you_have_something_better_to_do@account-cache:6379/0}

      MM_APP_PORT: ${MM_APP_PORT:-7789}
      MM_CACHE_URL: ${MM_CACHE_URL:-redis://:dont_you_have_something_better_to_do_too@game-cache:6379/0}
    depends_on:
      account-db:
        condition: service_healthy
        restart: true
      account-cache:
        condition: service_healthy
      game-cache:
        condition: service_healthy

  #############################################################################
  ## ACCOUNT
  #############################################################################
  account-db:
    image: postgres:17-alpine
    volumes: 
      - account-main-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${ACC_DB_PASS:-dont_you_have_something_better_to_do}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 3s
      timeout: 10s

  account-cache:
    image: valkey/valkey:8-alpine
    command: "valkey-server --save 60 1 --loglevel warning" # Fine-tune later
    volumes:
      - account-cache-vol:/data
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping"]
      interval: 10s
      retries: 5
      start_period: 3s
      timeout: 10s

  #############################################################################
  ## Game
  #############################################################################
  game-cache:
    image: valkey/valkey:8-alpine
    command: "valkey-server --save 60 1 --loglevel warning" # Fine-tune later
    volumes:
      - game-cache-vol:/data
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping"]
      interval: 10s
      retries: 5
      start_period: 3s
      timeout: 10s

  #############################################################################
  ## Message Broker
  #############################################################################
  broker:
    image: apache/kafka:3.8.1
    ports:
      - 19092:19092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://localhost:9092,EXTERNAL://broker:19092,controller://broker:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9092,EXTERNAL://broker:19092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: controller:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
volumes:
  account-main-vol:
  account-cache-vol:
  game-cache-vol:
