FROM node:22-alpine

WORKDIR /app

COPY ./package*.json .
COPY ./account/package*.json /app/account/
COPY ./lib/package*.json /app/lib/
RUN npm ci

COPY ./account /app/account
COPY ./lib /app/lib

ENTRYPOINT ["/app/account/docker-entrypoint.sh"]
